version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: development
      POSTGRES_DB: shitter_backend
    volumes:
      - /var/www/shitter_backend/db:/var/lib/postgresql/data

  redis:
    image: redis

  django:
    build: .
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      DATABASE_URL: postgres://admin:development@postgres:5432/shitter_backend
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    links:
      - postgres
      - redis
