# Generated by Django 3.0.8 on 2020-08-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollow',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='from user'),
        ),
    ]
