# Generated by Django 3.0.8 on 2020-08-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shit',
            name='reshit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shitter.Shit', verbose_name='reshit'),
        ),
    ]
