# Generated by Django 3.0.8 on 2020-08-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shitter', '0003_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='shit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='shitter.Shit', verbose_name='favourites'),
        ),
    ]
