# Generated by Django 3.0.8 on 2020-08-02 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shitter', '0004_auto_20200802_1915'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'shit')},
        ),
        migrations.AlterUniqueTogether(
            name='reshit',
            unique_together={('user', 'shit')},
        ),
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together={('from_user', 'to_user')},
        ),
    ]
