# Generated by Django 3.0.8 on 2020-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200802_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile-pictures'),
        ),
    ]
