# Generated by Django 3.0.8 on 2020-08-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200802_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cif',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private',
            field=models.BooleanField(default=False, verbose_name='private account'),
        ),
    ]
